export const POST_ANSWER_START = 'POST_ANSWER_START';
export const POST_ANSWER_END = 'POST_ANSWER_END';

export const GET_ANSWERS_START = 'GET_ANSWERS_START';
export const GET_ANSWERS_END = 'GET_ANSWERS_END';
