export const POST_TEAM_MEMBER_START = 'POST_TEAM_MEMBER_START';
export const POST_TEAM_MEMBER_END = 'POST_TEAM_MEMBER_END';

export const GET_TEAM_MEMBERS_START = 'GET_TEAM_MEMBERS_START';
export const GET_TEAM_MEMBERS_END = 'GET_TEAM_MEMBERS_END';

export const DELETE_TEAM_MEMBER_START = 'DELETE_TEAM_MEMBER_START';
export const DELETE_TEAM_MEMBER_END = 'DELETE_TEAM_MEMBER_END';
